### ISSUE TITLE
504 Gateway timeout errors

### ISSUE THREAD

**Issue by stefanlesik** [cytopia/devilbox#234]
Hi - I'm getting 504 timeout errors and general performance issues, especially when trying to access wp-admin across various sites within auto DNS. Any ideas? I'm on:

OSX High Sierra
Docker Version 18.03.0-ce-mac60 (23751)
Compose: 1.20.1

Here's my .env attached
[env.txt](https://github.com/cytopia/devilbox/files/1947848/env.txt)

**Comment by cnewfeldt** [comment]
Seeing the same thing with Docker Engine: 18.03.1-ce, Compose: 1.21.1. Recently updated docker and an apple security patch which required a restart. Now getting 504 gateway timeout errors on /wp-admin.

**Comment by cnewfeldt** [comment]
hmm, well, went to dive in to the issue this evening and it's working now ¯\_(ツ)_/¯ it may have been the network I was on today. I will check again tomorrow.

**Comment by cytopia** [comment]
@stefanlesik please attach output from `docker-compose logs` as well as the log files from `./log/` for your httpd and php version.

**Comment by adammarton** [comment]
Same on Windows 10, Docker 18.03.1-ce-win65 (17513).

**Comment by JakubHelis** [comment]
Same on Manjaro, 504, restart of docker (sql) temp fix it

**Comment by cytopia** [comment]
@JakubHelis  @adammarton @cnewfeldt @stefanlesik 
I just merged an update for the webserver. Could you try again please after pulling latest master branch.

**Comment by JakubHelis** [comment]
@cytopia  
For me it's still the same. + reloading the query (refresh page, retry ajax)  mostly gives positive result ( working)

**Comment by JakubHelis** [comment]
@cytopia  Interesting fact - The troubles gone when i switch from apache 2.4 to ngnix.   ( newest version of devilbox)

**Comment by cytopia** [comment]
@JakubHelis thanks for the heads up

**Comment by science695** [comment]
I also have mac users using my setup where devilbox just gets "angry" and my php code stops responding....usually fixed by a docker-compose stop && docker-compose start

**Comment by pauloffb** [comment]
Host machine with Linux Manjaro, also experiencing 504 Gateway on admin panel of Prestashop projects. Seems better after changing Apache 2.4 to 2.2.

**Comment by cytopia** [comment]
Anyone having this issue on a different web server than Apache 2.4?

**Comment by adammarton** [comment]
Yes, on nginx-stable, but this might be because of my raped WordPress instance.

**Comment by cytopia** [comment]
What about increasing timeout value of Apache 2.4

Create this file: `cfg/apache-2.4/timeout.cfg`
```ini
Timeout 600
```

**Comment by science695** [comment]
in my issue, the code running should not take 60 seconds, but when this occurs, its like php fpm is frozen. And changing the timeout would just make it wait longer before reporting back.

I wonder if it may be related to database connections used in the php code when it hangs.

**Comment by cytopia** [comment]
I might have found a proxy timeout overwrite by adding a vhost-gen template to the project which has timeouts (How to here: https://devilbox.readthedocs.io/en/latest/configuration-project/custom-vhost.html)

If this is the catch I will increase the Proxy timeout by default. Please let me know how it goes

The specific line is this:
```yaml
    # enablereuse requires Apache 2.4.11 or later
    <Proxy "fcgi://php:9000/" enablereuse=on max=10>
        ProxySet timeout=3600
        ProxySet connectiontimeout=3600
    </Proxy>
```

The full template is for `apache24.yml` is here:
```yml
---

# Apache 2.4 vHost Template defintion for vhost-gen.py
#
# The 'feature' section contains optional features that can be enabled via
# conf.yml and will then be replaced into the main vhost ('structure' section)
# into their corresponding position:
#
#    __XDOMAIN_REQ__
#    __PHP_FPM__
#    __ALIASES__
#    __DENIES__
#    __STATUS__
#
# The features itself also contain variables to be adjusted in conf.yml
# and will then be replaced in their corresponding feature section
# before being replaced into the vhost section (if enabled):
#
# PHP-FPM:
#    __PHP_ADDR__
#    __PHP_PORT__
# XDomain:
#    __REGEX__
# Alias:
#    __REGEX__
#    __PATH__
# Deny:
#    __REGEX__
# Status:
#    __REGEX__
#
# Variables to be replaced directly in the vhost configuration can also be set
# in conf.yml and include:
#    __VHOST_NAME__
#    __DOCUMENT_ROOT__
#    __INDEX__
#    __ACCESS_LOG__
#    __ERROR_LOG__
#    __PHP_ADDR__
#    __PHP_PORT__
#


###
### Basic vHost skeleton
###
vhost: |
  <VirtualHost __DEFAULT_VHOST__:__PORT__>
      ServerName   __VHOST_NAME__

      CustomLog  "__ACCESS_LOG__" combined
      ErrorLog   "__ERROR_LOG__"

  __REDIRECT__
  __SSL__
  __VHOST_DOCROOT__
  __VHOST_RPROXY__
  __PHP_FPM__
  __ALIASES__
  __DENIES__
  __SERVER_STATUS__
      # Custom directives
  __CUSTOM__
  </VirtualHost>

###
### vHost Type (normal or reverse proxy)
###
vhost_type:
  # Normal vHost (-p)
  docroot: |
    # Define the vhost to serve files
    DocumentRoot "__DOCUMENT_ROOT__"
    <Directory "__DOCUMENT_ROOT__">
        DirectoryIndex __INDEX__

        AllowOverride All
        Options All

        RewriteEngine on
        RewriteBase /

        Order allow,deny
        Allow from all
        Require all granted
    </Directory>

  # Reverse Proxy (-r)
  rproxy: |
    # Define the vhost to reverse proxy
    ProxyRequests off
    ProxyPass __LOCATION__ __PROXY_PROTO://__PROXY_ADDR__:__PROXY_PORT__
    ProxyHTMLURLMap __PROXY_PROTO://__PROXY_ADDR__:__PROXY_PORT__ __LOCATION__
    <location __LOCATION__>
        ProxyPassReverse /
        SetOutputFilter  proxy-html
        ProxyHTMLURLMap  /      __LOCATION__
        ProxyHTMLURLMap  __LOCATION__  __LOCATION__
        RequestHeader    unset  Accept-Encoding
    </location>


###
### Optional features to be enabled in vHost
###
features:

  # SSL Configuration
  ssl: |
    SSLEngine on
    SSLCertificateFile    "__SSL_PATH_CRT__"
    SSLCertificateKeyFile "__SSL_PATH_KEY__"
    SSLProtocol           __SSL_PROTOCOLS__
    SSLHonorCipherOrder   __SSL_HONOR_CIPHER_ORDER__
    SSLCipherSuite        __SSL_CIPHERS__

  # Redirect to SSL directive
  redirect: |
    RedirectMatch (.*) https://__VHOST_NAME__:__SSL_PORT__$1

  # PHP-FPM will not be applied to a reverse proxy!
  php_fpm: |
    # PHP-FPM Definition
    <FilesMatch \.php$>
        Require all granted
        SetHandler proxy:fcgi://__PHP_ADDR__:__PHP_PORT__
    </FilesMatch>

    # enablereuse requires Apache 2.4.11 or later
    <Proxy "fcgi://__PHP_ADDR__:__PHP_PORT__/" enablereuse=on max=10>
        ProxySet timeout=3600
        ProxySet connectiontimeout=3600
    </Proxy>

    # If the php file doesn't exist, disable the proxy handler.
    # This will allow .htaccess rewrite rules to work and
    # the client will see the default 404 page of Apache
    RewriteCond %{REQUEST_FILENAME} \.php$
    RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_URI} !-f
    RewriteRule (.*) - [H=text/html]

  alias: |
    # Alias Definition
    Alias "__ALIAS__" "__PATH____ALIAS__"
    <Location "__ALIAS__">
    __XDOMAIN_REQ__
    </Location>
    <Directory "__PATH____ALIAS__">
        Order allow,deny
        Allow from all
        Require all granted
    </Directory>

  deny: |
    # Deny Definition
    <FilesMatch "__REGEX__">
        Order allow,deny
        Deny from all
    </FilesMatch>

  server_status: |
    # Status Page
    <Location __REGEX__>
        SetHandler server-status
        Order allow,deny
        Allow from all
        Require all granted
    </Location>

  xdomain_request: |
    # Allow cross domain request from these hosts
    SetEnvIf Origin "__REGEX__" AccessControlAllowOrigin=$0
    Header add Access-Control-Allow-Origin %{AccessControlAllowOrigin}e env=AccessControlAllowOrigin
    Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
    Header always set Access-Control-Max-Age "0"
    Header always set Access-Control-Allow-Headers "x-requested-with, Content-Type, origin, authorization, accept, client-security-token"
    # Added a rewrite to respond with a 200 SUCCESS on every OPTIONS request.
    RewriteEngine On
    RewriteCond %{REQUEST_METHOD} OPTIONS
    RewriteRule ^(.*)$ $1 [R=200,L]
```


Once the template is applied, restart the devilbox and enter the webserver (`docker-compose exec httpd bash`) to see if those changes are actually picked up for the speicifc vhost

**Comment by cytopia** [comment]
Also let me now after what time the `Gateway Timeout` error appears (roughly in seconds).

What did you set your PHP's `max_execution_time` to?

**Comment by cytopia** [comment]
@qlstudent 

1. did you try this: https://github.com/cytopia/devilbox/issues/234#issuecomment-399342207?
2. Please also provide more information so that I can actually reproduce this issue:

> I have the same issue as well in Mac OS El Capitan. I switched from PHP 7.2 to PHP 5.6 and I have 504 error

For intranet or projects? If for projects, please let me know which Framework and for what requests

> and also some sites show up as they don't have /etc/hosts entry even though they totally do.

Can you attach a screenshot of the vhost overview with open console

**Comment by science695** [comment]
@cytopia I was able to fix / mitigate my issue by changing some php fpm settings.

I've read some things that say php-fpm children have problems after handling enough requests and its better if it is set to stop and start a replacement child.

I used ab (apache benchmark) to cause the errors, and after these pool changes, I cannot reproduce it.
`ab -r -n 5000 -c 100 https://devilbox.loc/vhosts.php`
(Note: this benchmarking will use all your system resources. my CPU fans were going at full speed while running this)

pool.conf changes:
```
pm.max_children = 100
pm.start_servers = 20
pm.max_requests = 500
```

**Comment by qlstudent** [comment]
I get these as well with wordpress. 

![screenshot from 2018-07-30 13-24-11](https://user-images.githubusercontent.com/38367184/43412663-edf609ca-93fb-11e8-91c5-97d3327595f8.png)

```
student@student-HP-EliteDesk-800-G1-SFF:~$ cat src/devilbox/.env 
###
###  ---------------------------------------------------
###  D E V I L B O X   R U N - T I M E   S E T T I N G S
###  ---------------------------------------------------
###
###  All the following settings are applied during
###  $ docker-compose up
###
###  No need to rebuild any dockers!
###
###  For custom variables, scroll to the bottom
###


###
### Show all executed commands in each
### docker image during docker-compose up?
###
### 1: Yes
### 0: No
DEBUG_COMPOSE_ENTRYPOINT=1


###
### Log to file or Docker logs.
###
### Logging to file means log files are available under log/
### on your host operating system.
### Logging to Docker logs means log files are streamed to
### stdout and stderr.
###
### 1: Log to Docker logs
### 0: Log to file
###
DOCKER_LOGS=0


###
### Relative or absolute path to the devilbox repository.
### (Used as a prefix for all mount paths)
### There is no need to change this.
###
### The only exception is for OSX users wanting to use NFS
### mounts instead of Filesystem mounts due to degraded performance
### on OSX.
###
### Note: When changing this variable you must re-create the container.
###       Simply remove it, it will be auto-created during the next start:
###
### $ docker-compose rm -f
###
DEVILBOX_PATH=.


###
### At what IP address should the docker services listen
### on the Host computer?
###
### The specified default should be fine for Linux and OSX (127.0.0.1:).
### If you are on windows, you will probably have to change
### it to the IP address of the docker machine.
###
### a.) Leave blank, to listen on all interfaces (no trailing color ':')
###    LOCAL_LISTEN_ADDR=
### b.) If an IP is specified, note the trailing colon ':'
###    LOCAL_LISTEN_ADDR=127.0.0.1:
###
LOCAL_LISTEN_ADDR=


###
### This is the domain suffix your projects will be made available
### with mass-virtual-hosting.
### It is also required for the internal DNS server to be setup.
###
### Note: Only ALPHA ([a-zA-Z]+) characters are supported.
###
### Example:
###   TLD_SUFFIX=loc
### Makes your project available under xxxx.loc
###
### Example:
###   TLD_SUFFIX=local
### Makes your project available under xxxx.local
###
TLD_SUFFIX=loc


###
### Optional DNS configuration
### Allows you to add extra DNS records (above the wildcard entry)
### Useful if your host computer run other Docker services that you want to connect to or reach
### from within the Devilbox network by a custom hostname.
###
### Format:
### -------
### Resolve any custom defined hostname to an IP address (useable inside container and host os)
###     EXTRA_HOSTS=<hostname>=<ip>[,<hostname>=<ip>]
###
### Resolve any custom defined hostname to whatever IP address a CNAME resolves to
### (Useable inside the container and host OS).
### Note: CNAME must be resolvable by Google DNS
###     EXTRA_HOSTS=<hostname>=<CNAME>[,<hostname>=<CNAME>]
###
### Examples:
### ---------
### EXTRA_HOSTS=hostname.loc=1.2.3.4
### EXTRA_HOSTS=host.loc=1.2.3.4,host.example.org=3.4.5.6
EXTRA_HOSTS=


###
### Set your user id and group id
###
### This should be changed to the value of your local
### users uid and gid
###
### Type `id` on the terminal to find out your values
###
NEW_UID=1000
NEW_GID=1000


###
### Timezone for all dockers and service config files
###
TIMEZONE=Europe/Berlin




################################################################################
###
### INTRANET SETTINGS
###
################################################################################

###
### TLD_SUFFIX domains are checked if they are set in the
### host computer /etc/hosts or available via attached DNS server.
### Timeout is done on vhosts.php (intranet) via ajax calls.
### In order to keep performance, set this to a low value.
### DNS checks might not succeed in time on slow machines.
### If DNS is valid, but timeout is expired, set this to a higher value.
###
### DNS_CHECK_TIMEOUT value is how many seconds to time out
### Default is to timeout after 1 second (DNS_CHECK_TIMEOUT=1)
###
DNS_CHECK_TIMEOUT=1


###
### Devilbox UI SSL Certificate generation
###
### When using SSL each certificate requires names for which it is responsible:
### Common Name as well as alternative names.
###
### Specify comma separated hostnames below by which you want to access the Devilbox.
### Those hostnames will be included in the SSL certificate for the Devilbox intranet.
### This has nothing to do for SSL certificates for projects, it is just for the intranet
### itself.
###
DEVILBOX_UI_SSL_CN=localhost,*.localhost,devilbox,*.devilbox


###
### Devilbox UI Password protection enable/disable (1/0)
###
### Set DEVILBOX_UI_PROTECT to 1 in order to password protect the
### intranet.
###
### Example:
###   DEVILBOX_UI_PROTECT=1
###   DEVILBOX_UI_PROTECT=0
###
DEVILBOX_UI_PROTECT=0


###
### Devilbox UI Password
###
### When DEVILBOX_UI_PROTECT=1, use the following password
### to log in. The password can always be changed.
### When changing the password, make sure to restart your
### PHP container.
###
### Example:
###   DEVILBOX_UI_PASSWORD=my-very-secure-password
###   DEVILBOX_UI_PASSWORD=Some pass with spaces
###
### The default username is 'devilbox'
###
DEVILBOX_UI_PASSWORD=password


###
### Enable the Devilbox Intranet?
###
### Example:
###   DEVILBOX_UI_ENABLE=1
###   DEVILBOX_UI_ENABLE=0
###
DEVILBOX_UI_ENABLE=1



################################################################################
###
### 1. Choose Images (Version)
###
################################################################################

###
### You can choose any combination of httpd, mysql, postgresql or php.
### Each of them are fully compatible between one another.
###


###
### 1.1 Choose PHP Server Image
###
#PHP_SERVER=5.3
#PHP_SERVER=5.4
#PHP_SERVER=5.5
#PHP_SERVER=5.6
#PHP_SERVER=7.0
#PHP_SERVER=7.1
PHP_SERVER=7.2
#PHP_SERVER=7.3


###
### 1.2 Choose HTTPD Server Image
###
#HTTPD_SERVER=apache-2.2
HTTPD_SERVER=apache-2.4
#HTTPD_SERVER=nginx-stable
#HTTPD_SERVER=nginx-mainline


###
### 1.3 Choose MySQL Server Image
###
#MYSQL_SERVER=mysql-5.5
#MYSQL_SERVER=mysql-5.6
#MYSQL_SERVER=mysql-5.7
#MYSQL_SERVER=mysql-8.0
#MYSQL_SERVER=mariadb-5.5
#MYSQL_SERVER=mariadb-10.0
#MYSQL_SERVER=mariadb-10.1
#MYSQL_SERVER=mariadb-10.2
MYSQL_SERVER=mariadb-10.3
#MYSQL_SERVER=percona-5.5
#MYSQL_SERVER=percona-5.6
#MYSQL_SERVER=percona-5.7


###
### 1.4 Choose PostgreSQL Server Image
###
#PGSQL_SERVER=9.1
#PGSQL_SERVER=9.2
#PGSQL_SERVER=9.3
#PGSQL_SERVER=9.4
#PGSQL_SERVER=9.5
#PGSQL_SERVER=9.6
#PGSQL_SERVER=10.0
#PGSQL_SERVER=10.1
#PGSQL_SERVER=10.2
PGSQL_SERVER=10.3


###
### 1.5 Choose Redis Server Image
###
#REDIS_SERVER=2.8
#REDIS_SERVER=3.0
#REDIS_SERVER=3.2
REDIS_SERVER=4.0


###
### 1.6 Choose Memcached Server Image
###
#MEMCD_SERVER=1.4.21
#MEMCD_SERVER=1.4.22
#MEMCD_SERVER=1.4.23
#MEMCD_SERVER=1.4.24
#MEMCD_SERVER=1.4.25
#MEMCD_SERVER=1.4.26
#MEMCD_SERVER=1.4.27
#MEMCD_SERVER=1.4.28
#MEMCD_SERVER=1.4.29
#MEMCD_SERVER=1.4.30
#MEMCD_SERVER=1.4.31
#MEMCD_SERVER=1.4.32
#MEMCD_SERVER=1.4.33
#MEMCD_SERVER=1.4.34
#MEMCD_SERVER=1.4.35
#MEMCD_SERVER=1.4.36
#MEMCD_SERVER=1.4.37
#MEMCD_SERVER=1.4.38
#MEMCD_SERVER=1.4.39
#MEMCD_SERVER=1.5.0
#MEMCD_SERVER=1.5.1
#MEMCD_SERVER=1.5.2
#MEMCD_SERVER=1.5.3
#MEMCD_SERVER=1.5.4
MEMCD_SERVER=1.5.5
#MEMCD_SERVER=latest


###
### 1.7 Choose Mongo Server Image
###
#MONGO_SERVER=2.8
#MONGO_SERVER=3.0
#MONGO_SERVER=3.2
#MONGO_SERVER=3.4
#MONGO_SERVER=3.5
#MONGO_SERVER=3.6
MONGO_SERVER=3.7



################################################################################
###
### 2. Host Mounts (Your computer)
###
################################################################################

###
### Local filesystem path to www projects.
###
### Note: When changing this variable you must re-create the container.
###       Simply remove it, it will be auto-created during the next start:
###
### $ docker-compose rm -f
###
HOST_PATH_HTTPD_DATADIR=./data/www


###
### Local filesystem path to mysql/mariadb datadir.
###
### This can be an existing mysql data directory or empty.
### If it already is a mysql data directory with content,
### it will be mounted into the docker and used.
###
### If this directory is empty, a new mysql database will be
### created.
###
### Note: Inside this path, a subdirectory with the mysql|mariadb
###       version will be created where the actual data resides.
###       This is to protect databases from being altered by
###       newer or older mysql|mariadb server versions.
###
### Note: When changing this variable you must re-create the container.
###       Simply remove it, it will be auto-created during the next start:
###
### $ docker-compose rm -f
###
HOST_PATH_MYSQL_DATADIR=./data/mysql


###
### Local filesystem path to postgresql datadir.
###
### This can be an existing postgresql data directory or empty.
### If it already is a postgresql data directory with content,
### it will be mounted into the docker and used.
###
### If this directory is empty, a new postgresql database will be
### created.
###
### Note: Inside this path, a subdirectory with the postgresql
###       version will be created where the actual data resides.
###       This is to protect databases from being altered by
###       newer or older postgres server versions.
###
### Note: When changing this variable you must re-create the container.
###       Simply remove it, it will be auto-created during the next start:
###
### $ docker-compose rm -f
###
HOST_PATH_PGSQL_DATADIR=./data/pgsql


###
### Local filesystem path to mongodb datadir.
###
### This can be an existing mongodb data directory or empty.
### If it already is a mongodb data directory with content,
### it will be mounted into the docker and used.
###
### If this directory is empty, a new mongodb database will be
### created.
###
### Note: When changing this variable you must re-create the container.
###       Simply remove it, it will be auto-created during the next start:
###
### $ docker-compose rm -f
###
HOST_PATH_MONGO_DATADIR=./data/mongo



################################################################################
###
### 3. PHP Docker Settings
###
################################################################################

###
### Enable certain PHP modules which are not enabled by default
###
### Currently the only module that can be enabled is 'ioncube'
###
### PHP_MODULES_ENABLE=ioncube
###
PHP_MODULES_ENABLE=


###
### Disable any PHP modules that you don't require
###
### Specify a comma separated list without spaces of modules to disable
###
### PHP_MODULES_DISABLE=xdebug,imagick,swoole
###
PHP_MODULES_DISABLE=


###
### Configure everything else about PHP in
### * cfg/php-ini-X.X/*.ini
### * cfg/php-fpm-X.X/*.conf



################################################################################
###
### 4. HTTPD Docker Settings
###
################################################################################

###
### Expose HTTPD Port to Host
###
HOST_PORT_HTTPD=80
HOST_PORT_HTTPD_SSL=443


###
### Document Root Subdirectory
###
### In your project directory, which subfolder should
### serve your files?
###
### When changing this value, restart the devilbox.
###
HTTPD_DOCROOT_DIR=htdocs


###
### Per vHost Config Subdirectory
###
### In your project directory, which subfolder should
### hold apache, nginx templates for a customized vhost?
###
### When changing this value, restart the devilbox.
###
HTTPD_TEMPLATE_DIR=.devilbox



################################################################################
###
### 5. MySQL Docker Settings
###
################################################################################

###
### MySQL root user password
###
### If $HOST_PATH_MYSQL_DATADIR already contains an existing
### mysql datadir, enter the password for the existing mysql database
###
### If $HOST_PATH_MYSQL_DATADIR is empty, choose a new password that
### will be applied
###
MYSQL_ROOT_PASSWORD=


###
### Custom MySQL Runtime Settings
###
MYSQL_GENERAL_LOG=0


###
### Expose MySQL Port to Host
###
HOST_PORT_MYSQL=3306



################################################################################
###
### 6. PostgreSQL Docker Settings
###
################################################################################

###
### PostgreSQL 'root' user name (usually postgres)
###
PGSQL_ROOT_USER=postgres


###
### PostgreSQL 'root' user password
###
PGSQL_ROOT_PASSWORD=


###
### Expose PostgreSQL Port to Host
###
HOST_PORT_PGSQL=5432



################################################################################
###
### 7. Redis Docker Settings
###
################################################################################

###
### Expose Redis Port to Host
###
HOST_PORT_REDIS=6379



################################################################################
###
### 8. Memcached Docker Settings
###
################################################################################

###
### Expose Memcached Port to Host
###
HOST_PORT_MEMCD=11211



################################################################################
###
### 9. MongoDB Docker Settings
###
################################################################################

###
### Expose MongoDB Port to Host
###
HOST_PORT_MONGO=27017



################################################################################
###
### 10. Bind Docker Settings
###
################################################################################

###
### Expose Bind Port to Host
###
HOST_PORT_BIND=1053

###
### Add comma separated DNS server from which you want to receive DNS
### You can also add DNS servers from your LAN (if any are available)
###
BIND_DNS_RESOLVER=8.8.8.8,8.8.4.4

###
### Validate DNSSEC
###
### Values:
###  no:    DNSSEC validation is disabled
###  yes:   DNSSEC validation is enabled, but a trust anchor must be manually configured.
###  auto:  DNSSEC validation is enabled, and a default trust anchor for root zone is used.
###
BIND_DNSSEC_VALIDATE=no


###
### Bind timing options (time in seconds)
###
### Leave empty for defaults.
### Only change when you know what you are doing.
###
BIND_TTL_TIME=
BIND_REFRESH_TIME=
BIND_RETRY_TIME=
BIND_EXPIRY_TIME=
BIND_MAX_CACHE_TIME=


###
### Show DNS Queries in Docker logs output?
###
### 1: Yes
### 0: No
BIND_LOG_DNS_QUERIES=0



################################################################################
###
### 11. Custom variables
###
################################################################################

###
### Any variable defined in this file will be available
### as environment variables to your PHP/HHV Docker container.
###
### This might be useful to set application environment and retrieve
### them via: <?php getenv('MY_APPLICATION_ENV'); ?>
###


###
### Example:
### <?php echo getenv('Foo'); ?> would produce: 'some value'
###
#Foo=some value
student@student-HP-EliteDesk-800-G1-SFF:~$ 

```

**Comment by cytopia** [comment]
## Successfully tested settings

I have now benchmarked it with PrestaShop and Magento as they are pretty performance hungry.
Additionally only tested HTTPS to get even more performance penalty:

* https://devilbox.readthedocs.io/en/latest/examples/setup-presta-shop.html
* https://devilbox.readthedocs.io/en/latest/examples/setup-magento.html

**Container:**

* **PHP:** PHP-FPM 7.1
* **HTTPD:** Apache 2.4


**HTTPS with keep alive**
```
ab -r -n 5000 -c 100 -v 2 -k  https://presta.loc/en/ 2>/dev/null | grep ^HTTP
ab -r -n 5000 -c 100 -v 2 -k  https://magento/ 2>/dev/null | grep ^HTTP
```

**HTTPS without keep alive**
```
ab -r -n 5000 -c 100 -v 2 https://presta.loc/en/ 2>/dev/null | grep ^HTTP
ab -r -n 5000 -c 100 -v 2 https://magento/ 2>/dev/null | grep ^HTTP
```

After a lot of back and forth I now came to the following balance between initial RAM consumption and not throwing 500s:

```ini
[www]
pm.max_children = 50
pm.start_servers = 10
pm.min_spare_servers = 5
pm.max_spare_servers = 15
pm.max_requests = 500
```

## Please test

@stefanlesik @cnewfeldt @adammarton @JakubHelis @science695 @pauloffb @qlstudent 

Can you please test the new PHP-FPM configuration and report back how this works.

## How to apply the configuration?

To set this up read on here: https://devilbox.readthedocs.io/en/latest/configuration-files/php-fpm-conf.html

**Comment by chrizz1001** [comment]
As far as I can tell (after a day of work) the config fixes the problem.

**Comment by cytopia** [comment]
@chrizz1001 good to hear.

I will have another few commits coming soon to generalize the configuration accross all PHP versions. This will lead to new Docker images. I will update here once they are pushed to the above specified PR.

**Comment by cytopia** [comment]
Another thing I just found out is that Apache 2.4 is keeping the connection to the PHP-FPM processes up, thus the PHP-FPM processes cannot respawn and get not drowned. I will add a patch for it as well.

**Comment by cytopia** [comment]
## Changed default settings for performance

I have now switched from `pm = dynamic` to `pm = ondemand`. This has the benefit that the initial RAM consumption of the PHP container is at around 50-60 Megabytes in total.

Workers are spawned ondemand and will also be released after 10sec of inactivity, meaning if nothing happens the RAM consumption goes back to 50-60 Megabytes.

Nevertheless I have benched it with `ab` and the results are very promising.

Defaults for PHP are available here: 
* https://github.com/devilbox/docker-php-fpm/blob/master/build/ansible/group_vars/all.yml#L26
* https://github.com/devilbox/docker-php-fpm/tree/master/build/ansible/CONFIGURATION

#### php-fpm.conf
```ini
[global]
log_level = notice

[www]
request_terminate_timeout = 120s
listen.backlog = 128
pm = ondemand
pm.max_children = 50
pm.start_servers = 4
pm.min_spare_servers = 2
pm.max_spare_servers = 6
pm.max_requests = 500
pm.process_idle_timeout = 10s
```


#### php.ini
```ini
memory_limit		= 512M

max_execution_time      = 120
max_input_time          = 120

post_max_size           = 72M
upload_max_filesize     = 64M
max_file_uploads        = 20

variables_order         = EGPCS
max_input_vars          = 8000
max_input_nesting_level = 64

error_reporting         = E_ALL | E_NOTICE | E_STRICT | E_DEPRECATED
xmlrpc_errors           = Off
report_memleaks         = On
display_errors          = On
display_startup_errors  = On
track_errors            = On
log_errors              = On
html_errors             = On

xdebug.default_enable   = Off
xdebug.profiler_enable  = Off
xdebug.remote_enable    = Off
xdebug.remote_autostart = Off
```

## Web server changes

Those will be available later this day in a new PR.

**Comment by cytopia** [comment]
Travis-CI seems to have some problems and therefore the images are not yet available: https://www.traviscistatus.com/incidents/118bjpkgkg00

**Comment by cytopia** [comment]
`liste.backlog = 128` was way too low. I've set it to `1024` now and waiting for the images to be pushed to Dockerhub.

**Comment by cytopia** [comment]
PR is up: https://github.com/cytopia/devilbox/pull/338
