### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by dbd5** [cytopia/devilbox#586]
[env.txt](https://github.com/cytopia/devilbox/files/3240904/env.txt)

### ISSUE TYPE

 - Bug Report

### Checklist

* [X ] `.env` file is attached
* [ ] `docker-compose.override.yml` is attached (if it exists)
* [ ] Custom configs from `cfg/` dir are attached (if customized)
* [ ] `docker-compose logs` and `log/` output is added
* [X] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [X] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [X] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

### OS / ENVIRONMENT

1. Host operating system and version: MacOs High Siera 10.13.6
2. (Windows) Native Docker or Docker Toolbox: 
3. Docker version: Docker Desktop 2.0.0.3
4. Docker Compose version: Docker Compose: 1.23.2
5. (Linux) Is SELinux enabled?:No
6. What git commit hash are you on?:

### SUMMARY

Unable to connect to external network or internet from inside devilbox shell the error message after timeout is "**Temporary failure in name resolution**"

### STEPS TO REPRODUCE

1. Install docker desktop
2. Start docker desktop
3. Install devilbox
4. Copy env-example to .env and update as in attached config
5. Confirm internet access from OS host
6. Start the environment with docker-compose up -d httpd php mysql bind mongo
7. Get into the shell with ./shell.sh
7. Ping any internet address

### EXPECTED BEHAVIOUR

Access to the internet should be available via ping or curl

### ACTUAL BEHAVIOUR

Connection attempt times out with Temporary failure in name resolution

### OTHER INFORMATION
1. When I initially setup, I didn't know that port 53 should be available on the host machine (according to the PDF documentation - Section 12.1.1 - Setup Auto DNS for Native docker) but I have since removed DNSMASQ, the service using port 53 on the host machine.

2. I observe that lsof -nP -i4TCP:53 shows a new service using port 53 as docker?
com.docke 757 dbd5   20u  IPv4 0xe56e254becfb75      0t0  TCP 127.0.0.1:53 (LISTEN)
Not sure this is good, considering that the documentation sys port 53 should be available;

3. My resolv.conf content is
nameserver: 127.0.0.11
options ndots:0

#### Start command

```
docker-compose up -d httpd php mysql bind mongo
```

#### File and user permissions (Linux & MacOS)

```
user = 501
group = 20
```

```
$ ls -la
```

```
$ ls -la data/www
```

**Comment by dbd5** [comment]
Resolved

**Comment by aquaswim** [comment]
how you resolve this issue ?? i still can't resolve domain name from container.

**Comment by patarok** [comment]
May I gently ask: How for Christs sake, did you solve the problem? PLS? 
Because I am pretty sure, to add the local DNS in the .env by BIND_DNS_RESOLVER does not solve this.
