### ISSUE TITLE
no working mysql image

### ISSUE THREAD

**Issue by Chris25602** [cytopia/devilbox#643]
1. Host operating system and version: Windows 10 Pro version 1903 build 18362.418
2. (Windows) Native Docker or Docker Toolbox: Docker Desktop v2.1.0.4 (39773)
3. Docker version: Engine 19.03.04
4. Docker Compose version: 1.24.1
5. (Linux) Is SELinux enabled?:  N/A
6. What git commit hash are you on?: 0543f2da9218661824c64148e07f601f5e99f302

git clone ...
vi .env
select any version of mysql in the .env file

#MYSQL_SERVER=mysql-5.5
#MYSQL_SERVER=mysql-5.6
MYSQL_SERVER=mysql-5.7
#MYSQL_SERVER=mysql-8.0

start container ... docker-compose up

mysql will fail on all versions

EXPECTED BEHAVIOUR
a container with an available version of Mysql

ACTUAL BEHAVIOUR
Cannot use Mysql

**Comment by cytopia** [comment]
@Chris25602 can you attach the `docker-compose logs` here.

**Comment by souhaiebtar** [comment]
the same problem happen for me but only for `mysql-8.0` `mariadb-` 10.1, 10.2 and 10.3,
i tested `mysql 5.5, 5.6, 5.7` and `mariadb-5.5`, `mariadb-10.0` work fine, i didn't test `percona`,

OS: ubuntu 18.04.3
docker version: 19.03.5,
commit id: `9234730`
firewall status: inactive (uwf)

**Comment by cytopia** [comment]
Please update to the latest Devilbox version and post your start command, docker logs and `.env` file contents.

**Comment by RockyKev** [comment]
Same issue, on a windows 10. 

* [x] `.env` file is attached [env.txt](https://github.com/cytopia/devilbox/files/4531589/env.txt)
* [x] `docker-compose logs` and `log/` output is added  [log.txt](https://github.com/cytopia/devilbox/files/4531626/log.txt)

1. Host operating system and version: WIndows 10 Pro 1909
2. (Windows) Native Docker or Docker Toolbox: Docker Desktop
3. Docker version: Docker version 19.03.8, build afacb8b
4. Docker Compose version: docker-compose version 1.25.4, build 8d51620a
5. (Linux) Is SELinux enabled?: N/A
6. What git commit hash are you on?: 8c931cd

### SUMMARY


Mysql container isn't loading.

### STEPS TO REPRODUCE



1. Followed these [instructions here](https://devilbox.readthedocs.io/en/latest/getting-started/install-the-devilbox.html#download-the-devilbox) to pull a brand new Devilbox.
2. Attempted `docker-compose up -d httpd php mysql `
3. error

```
PS E:\2bDevelopment\devilbox2> docker-compose up -d httpd php mysql                                                     devilbox2_bind_1 is up-to-date
devilbox2_php_1 is up-to-date
devilbox2_httpd_1 is up-to-date
Starting devilbox2_mysql_1 ... error                                                                                    
ERROR: for devilbox2_mysql_1  Cannot start service mysql: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"mysql-entrypoint.sh\": executable file not found in $PATH": unknown

ERROR: for mysql  Cannot start service mysql: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"mysql-entrypoint.sh\": executable file not found in $PATH": unknown
ERROR: Encountered errors while bringing up the project.
```

**Comment by RockyKev** [comment]
Messed with the .env file and changed the sql version.
Working now.

```
###
### 1.3 Choose MySQL Server Image
###
#MYSQL_SERVER=mysql-5.5
#MYSQL_SERVER=mysql-5.6
#MYSQL_SERVER=mysql-5.7
MYSQL_SERVER=mysql-8.0
#MYSQL_SERVER=mariadb-5.5
#MYSQL_SERVER=mariadb-10.0
#MYSQL_SERVER=mariadb-10.1
#MYSQL_SERVER=mariadb-10.2
#MYSQL_SERVER=mariadb-10.3
#MYSQL_SERVER=mariadb-10.4
#MYSQL_SERVER=percona-5.5
#MYSQL_SERVER=percona-5.6
#MYSQL_SERVER=percona-5.7
#MYSQL_SERVER=percona-8.0
```

**Comment by cytopia** [comment]
Fixed here: https://github.com/cytopia/devilbox/pull/750

**Comment by hielh** [comment]
Hi @cytopia 
The problem still exist for devilbox/mysql:mysql-8.0.
When I start using this image I get postgres server and not mysql server:
![image](https://user-images.githubusercontent.com/909932/100724330-0b877c80-33c3-11eb-816f-2c997e271e68.png)

**Comment by cytopia** [comment]
> The problem still exist for devilbox/mysql:mysql-8.0.
> When I start using this image I get postgres server and not mysql server:

This is very strange.

Can you provide:
1. Full `docker-compose logs` output
2. Full `./check-config.sh` output

**Comment by hielh** [comment]
@cytopia 
[logs.log](https://github.com/cytopia/devilbox/files/5621936/logs.log)

[docker-compose.yml.txt](https://github.com/cytopia/devilbox/files/5621939/docker-compose.yml.txt)
[.env .txt](https://github.com/cytopia/devilbox/files/5621945/default.env.txt)

Full ./check-config.sh output  => I don't have it

**Comment by cytopia** [comment]
> Full ./check-config.sh output => I don't have it

Then you're on an older version, which also has older MySQL images. You should consider updating to `v1.8.3` and check if the issue is solved in this one.

**Comment by hielh** [comment]
@cytopia 
Please find attachement my logs
[logs.log](https://github.com/cytopia/devilbox/files/5628610/logs.log)
[check-config.log](https://github.com/cytopia/devilbox/files/5628611/check-config.log)
[.env (copy).txt](https://github.com/cytopia/devilbox/files/5628615/default.env.copy.txt)

Do you have an idea about origin of the problem

**Comment by cytopia** [comment]
Judging from your MySQL logs:
```
;1mmysql_1     |[0m 2020-12-02T10:30:46.577481Z 1 [ERROR] [MY-012530] [InnoDB] Unknown redo log format (103). Please follow the instructions at http://dev.mysql.com/doc/refman/8.0/en/ upgrading-downgrading.html.
```

You probably need to upgrade your databases:

1. I would make a backup via `mysqldump-secure`
2. Remove current volumes
```bash
 docker volume ls | grep mysql
local               devilbox2_devilbox-mysql-5.5
local               devilbox2_devilbox-mysql-5.6
local               devilbox2_devilbox-mysql-5.7
local               devilbox2_devilbox-mysql-8.0
```
3. Remove mysql container
```
docker-compose rm -f 
```
4. Recreate via `docker-compse up`
5. Insert backups

**Comment by hielh** [comment]
@cytopia 
Thank you it work's, but I had new problem on xdebug. I get as eror
`Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 xdebug 3`
