### ISSUE TITLE
502 Bad Gateway to Devilbox Intranet

### ISSUE THREAD

**Issue by taliptako** [cytopia/devilbox#697]
### ISSUE TYPE
 - Bug Report

1. Host operating system and version: Fedora 32
2. (Windows) Native Docker or Docker Toolbox: 
3. Docker version: Docker version 19.03.8, build afacb8b
4. Docker Compose version:  1.25.4
5. (Linux) Is SELinux enabled?: NO I disabled it
6. What git commit hash are you on?: 8c931cdf5636b08ffecd0c73cb40ec4afd239783

### SUMMARY
I just clone the devilbox repo set my .env then run docker-compose command on fresh Fedora 32 installation. Now I'm having this 502 Bad Gateway error
Log says
`2020/04/12 14:40:57 [error] 299#299: *12 connect() failed (113: No route to host) while connecting to upstream, client: 172.16.238.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.16.238.10:9000", host: "localhost"`

#### Start command
```
$ docker-compose up -d php mysql redis
```

[log.zip](https://github.com/cytopia/devilbox/files/4466506/log.zip)

[compose-env.zip](https://github.com/cytopia/devilbox/files/4466508/compose-env.zip)

**Comment by taliptako** [comment]
This is related with docker cause it works on Ubuntu since i move to Ubuntu LTS 20.04 i'm gonna let F32 users think about this :)

**Comment by cytopia** [comment]
Thanks for the heads-up

**Comment by science695** [comment]
@taliptako Can you trace pinging and checking the routes between your host, the php/http container? (you might have to apt update and apt install some network tool packages on http)

You could also try installing an older version of docker (a couple minor versions back)...

If you have both ubuntu anf F32, try comparing the routing tables between the 2 setups.

**Comment by DorianLsl** [comment]
@taliptako @cytopia
Being on Fedora 32, I had that problem too! But after hours of tearing my hair out, I found the solution.
Once the containers are launched, do an "ifconfig", normally a network interface of type "aa-acXXXXXXffXc" will appear.
You just have to identify this interface as a trusted interface for the firewall :
```
* firewall-cmd --permanent --zone=trusted --add-interface=aa-acXXXXXXffXc
* firewall-cmd --reload

**Comment by magosla** [comment]
I encountered the same issue while trying to access https://localhost. I noticed the issue occurs when I use compose from docker's CLI ```docker compose up``` but not experienced when I use ```docker-compose up```

Docker version 20.10.5, build 55c4c88
docker-compose version 1.29.0, build 07737305
Host OS: Windows 10

**Comment by Novitsh** [comment]
I have the same issue with `docker compose up`, fixed by still using `docker-compose up`.

**Comment by pedrosanta** [comment]
> I have the same issue with `docker compose up`, fixed by still using `docker-compose up`.

My issue exactly too.

**Comment by ailequal** [comment]
I ran into the same problem today with a fresh installation of macOS 10.15.7. I was still having problem even if I was using `docker-compose up`. Later I realized that I still needed to double check that the newer docker-compose version wasn't activated. You can do that through Docker Desktop's settings or by launching: `docker-compose disable-v2`

**Comment by obionex-5** [comment]
> I ran into the same problem today with a fresh installation of macOS 10.15.7. I was still having problem even if I was using `docker-compose up`. Later I realized that I still needed to double check that the newer docker-compose version wasn't activated. You can do that through Docker Desktop's settings or by launching: `docker-compose disable-v2`

Thank you it helped to fix the same issue. 
Can someone explain what happened and why v2 causes this issue? Thanks!

**Comment by Dennis4720** [comment]
> I ran into the same problem today with a fresh installation of macOS 10.15.7. I was still having problem even if I was using `docker-compose up`. Later I realized that I still needed to double check that the newer docker-compose version wasn't activated. You can do that through Docker Desktop's settings or by launching: `docker-compose disable-v2`

This worked for me aswel! Thank you so much for your reply and temporary solution. I hope this issue gets fixed soon but for now this works.

**Comment by catsAND** [comment]
> @taliptako @cytopia
> Being on Fedora 32, I had that problem too! But after hours of tearing my hair out, I found the solution.
> Once the containers are launched, do an "ifconfig", normally a network interface of type "aa-acXXXXXXffXc" will appear.
> You just have to identify this interface as a trusted interface for the firewall :
> 
> ```
> * firewall-cmd --permanent --zone=trusted --add-interface=aa-acXXXXXXffXc
> * firewall-cmd --reload
> ```

Thanks you. Its helped me.
